# Custom PostgreSQL queries for detailed monitoring

pg_database_size:
  query: |
    SELECT 
      datname as database,
      pg_database_size(datname) as size_bytes
    FROM pg_database
    WHERE datistemplate = false
  metrics:
  - database:
      usage: "LABEL"
      description: "Database name"
  - size_bytes:
      usage: "GAUGE"
      description: "Database size in bytes"

pg_table_size:
  query: |
    SELECT 
      schemaname,
      tablename,
      pg_total_relation_size(schemaname||'.'||tablename) as size_bytes,
      pg_relation_size(schemaname||'.'||tablename) as table_size_bytes,
      pg_total_relation_size(schemaname||'.'||tablename) - pg_relation_size(schemaname||'.'||tablename) as index_size_bytes
    FROM pg_tables
    WHERE schemaname NOT IN ('information_schema', 'pg_catalog')
  metrics:
  - schemaname:
      usage: "LABEL"
      description: "Schema name"
  - tablename:
      usage: "LABEL"
      description: "Table name"
  - size_bytes:
      usage: "GAUGE"
      description: "Total table size including indexes"
  - table_size_bytes:
      usage: "GAUGE"
      description: "Table size without indexes"
  - index_size_bytes:
      usage: "GAUGE"
      description: "Index size"

pg_slow_queries:
  query: |
    SELECT 
      query,
      calls,
      total_time,
      mean_time,
      rows,
      100.0 * shared_blks_hit / nullif(shared_blks_hit + shared_blks_read, 0) AS hit_percent
    FROM pg_stat_statements
    WHERE calls > 100
    ORDER BY mean_time DESC
    LIMIT 20
  metrics:
  - query:
      usage: "LABEL"
      description: "Query text"
  - calls:
      usage: "COUNTER"
      description: "Number of times executed"
  - total_time:
      usage: "COUNTER"
      description: "Total time spent in the statement"
  - mean_time:
      usage: "GAUGE"
      description: "Mean time spent in the statement"
  - rows:
      usage: "COUNTER"
      description: "Total number of rows retrieved or affected"
  - hit_percent:
      usage: "GAUGE"
      description: "Cache hit percentage"

pg_connections:
  query: |
    SELECT 
      state,
      count(*) as connections
    FROM pg_stat_activity
    WHERE state IS NOT NULL
    GROUP BY state
  metrics:
  - state:
      usage: "LABEL"
      description: "Connection state"
  - connections:
      usage: "GAUGE"
      description: "Number of connections in this state"

pg_locks:
  query: |
    SELECT 
      mode,
      locktype,
      count(*) as locks
    FROM pg_locks
    GROUP BY mode, locktype
  metrics:
  - mode:
      usage: "LABEL"
      description: "Lock mode"
  - locktype:
      usage: "LABEL"
      description: "Lock type"
  - locks:
      usage: "GAUGE"
      description: "Number of locks"
